[package]
name = "evalf"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Symmetrica numeric evaluation: arbitrary-precision float evaluation of symbolic expressions"

[lib]
path = "src/lib.rs"

[dependencies]
expr_core = { path = "../expr_core" }
