[package]
name = "algebraic"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "Algebraic numbers: quadratic extensions Q(sqrt(d)) basics"

[dependencies]
arith = { path = "../arith" }
