[package]
name = "summation"
version = "0.1.0"
edition.workspace = true

[dependencies]
expr_core = { path = "../expr_core" }
arith = { path = "../arith" }
polys = { path = "../polys" }
simplify = { path = "../simplify" }
