[package]
name = "matrix"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Symmetrica matrix/linear algebra module (stub)"

[lib]
path = "src/lib.rs"

[dependencies]
expr_core = { path = "../expr_core" }
arith = { path = "../arith" }
