[package]
name = "arith"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Shared arithmetic utilities: small rationals over i64 (tuple Rat and Q newtype)"

[lib]
path = "src/lib.rs"

[dev-dependencies]
proptest = "1.5"
