[package]
name = "io"
version = "1.0.0-rc.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Symmetrica I/O crate (stub): parser/printers"

[lib]
path = "src/lib.rs"

[dependencies]
expr_core = { path = "../expr_core" }

[dev-dependencies]
proptest = "1.5"
